Features branch
cindykandie/capstone-1 pull request #1
Opened 2023-01-04 15:24 UTC by cindykandie

## Creating a website page advertising a FIRE conference
- Set the right tools, images fonts and colours based on the design and finance topic 
- Create the pages ie home and about pages with mobile-first design
- Deployed the website
- Made the website responsive on larger screens
- Added the mobile menu to appear on clicking the hamburger menu
- Used Javascript instead of HTML to render the Speakers' list
- Find a live walkthrough of the site on this loom video: https://www.loom.com/share/a35ab94b868b406aaf5615345802dfbe
- More details on the README file

2023-01-04 17:15 UTC, amejid requested changes
Hi @cindykandie, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- Descriptive PR :heavy_check_mark: 
- Meaningful commits :heavy_check_mark: 
- Clean code :fire: :fire: :fire: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-04 17:15 UTC, amejid commented on index.html
> +    </section>
- [x] Kindly try to align these images in a single line on the desktop version to match the design as much as possible. 🤝️
- [x] Please add `alt` attributes for the images as it is incredibly useful for accessibility — screen readers read this description out to their users so they know what the image means. 🤓️

**Design**

![Screenshot from 2023-01-04 19-20-17](https://user-images.githubusercontent.com/17243325/210605262-69a98bcd-d708-4b46-bfa4-4a5bb590df4a.png)

2023-01-04 17:15 UTC, amejid commented on index.html
> +    </footer>
- [x] Kindly update the background of the footer as per the design. On the desktop version, the footer on the Home page should have a white background while the footer on the About page should have a dark background. On the mobile version, it should be the same white background for both the Home and About pages. 🧐️

**Home - Desktop**
![Screenshot from 2023-01-04 19-18-23](https://user-images.githubusercontent.com/17243325/210607718-e99dd26c-2088-454c-ac07-5d6f16ff7130.png)

**About - Desktop**
![Screenshot from 2023-01-04 19-17-45](https://user-images.githubusercontent.com/17243325/210607710-db3836ad-98ee-4907-bafb-c8c43b178069.png)

2023-01-04 17:15 UTC, amejid commented on index.html
> +                    <img src="assets/fire2.jpg" alt="">
- [x] Please add `alt` attribute for the image.

2023-01-04 17:15 UTC, amejid commented on index.html
> +                    <img src="assets/lecture.png" alt="">
- [x] Please add `alt` attribute for the image. ✍️

2023-01-04 17:15 UTC, amejid commented on index.html
> +                    <img src="assets/presentation.png" alt="">
- [x] Please add `alt` attribute for the image. ✍️

2023-01-04 17:15 UTC, amejid commented on index.html
> +                    <img src="assets/forum.png" alt="">
- [ ] Please add `alt` attribute for the image. ✍️

2023-01-04 17:15 UTC, amejid commented on index.html
> +                    <img src="assets/chat.png" alt="">
- [ ] Please add `alt` attribute for the image. ✍️

2023-01-04 17:15 UTC, amejid commented on index.html
> +                    <img src="assets/fire-round-button.png" alt="">
- [ ] Please add `alt` attribute for the image. ✍️

2023-01-04 17:15 UTC, amejid commented on index.html
> +        </ul>
- [ ] Please update the size of the images in this section. They look a bit smaller on the desktop version when compared to the design. 🤝️

**Design**
![Screenshot from 2023-01-04 19-16-02](https://user-images.githubusercontent.com/17243325/210610326-96771dca-eeac-4695-9b75-3e03a44a4946.png)

**Your work**
![Screenshot from 2023-01-04 19-16-19](https://user-images.githubusercontent.com/17243325/210610337-088bfe2d-bdc9-4594-ae81-f57c470b6eab.png)

2023-01-04 17:15 UTC, amejid commented on aboutpage.html
> +                    <img src="assets/facebook.png" alt="">
- [ ] Please add `alt` attribute for the image. ✍️

2023-01-04 17:15 UTC, amejid commented on aboutpage.html
> +                        <img src="assets/twitter.png" alt="">
- [ ] Please add `alt` attribute for the image. ✍️

2023-01-04 17:15 UTC, amejid commented on aboutpage.html
> +                    <img src="assets/fire2.jpg" alt="">
- [ ] Please add `alt` attribute for the image. ✍️

2023-01-04 17:15 UTC, amejid commented on aboutpage.html
> +        <img src="assets/fire2.jpg" alt="">
- [ ] Please add `alt` attribute for the image. ✍️

2023-01-04 17:15 UTC, amejid commented on aboutpage.html
> +                <img src="assets/event1.jpg" alt="">
- [ ] Please add `alt` attribute for the image. ✍️

2023-01-04 17:15 UTC, amejid commented on aboutpage.html
> +                <img src="assets/event2.jpg" alt="">
- [ ] Please add `alt` attribute for the image. ✍️

2023-01-04 17:15 UTC, amejid commented on aboutpage.html
> +        </div>
- [ ] Please add `alt` attribute for the image. ✍️

2023-01-04 22:01 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @cindykandie 

Your project is complete! Great job for making the requested changes 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ Design well followed
✅ Readme well personalized

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

![tufoin](https://media.giphy.com/media/PZ0cjwaldbX7ArSRn1/giphy.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-04 22:01 UTC, tufoinnkuo10 commented on js/modals.js
> +const hamBurger = document.querySelector('nav.mobile-nav div');
- [optional] please, maybe the previous reviewer didn't notice, but it will make your app look more professional. Please ensure when the mobile menu pops up, they cannot see your site scrolling behind it.
![demo33](https://user-images.githubusercontent.com/65298048/210657778-9d14fe5e-fc1e-4ac7-b783-896822e0aef2.gif)

2023-01-05 08:06 UTC, merged

2023-01-13 07:22 UTC, wickathou commented on css/aboutpage.css
> +.contact {
Recommended to use generic classes that can be reused, to avoid repeating properties across multiple ones